TEST_DURATION_SECONDS = 120

NO_FACE_GRACE_PERIOD = 3
FACE_ALIGNMENT_GRACE_PERIOD = 5
VIOLATION_GRACE_PERIOD = 3

MAX_VIOLATIONS = 2

FACE_MIN_AREA_RATIO = 0.05
FACE_MAX_AREA_RATIO = 0.25

HEAD_MOVE_THRESHOLD = 15
EYE_MOVEMENT_THRESHOLD = 0.35
