TEST_DURATION_SECONDS = 180

NO_FACE_GRACE_PERIOD = 3
FACE_ALIGNMENT_GRACE_PERIOD = 3
VIOLATION_GRACE_PERIOD = 3

MAX_VIOLATIONS = 30

FACE_MIN_AREA_RATIO = 0.05
FACE_MAX_AREA_RATIO = 0.22

# Head pose (MediaPipe normalized units)
HEAD_YAW_THRESHOLD = 0.10     # 10% left/right
HEAD_PITCH_THRESHOLD = 0.08   # 8% up/down

# Eye movement
EYE_MOVEMENT_THRESHOLD = 0.35

# Timers
HEAD_MOVEMENT_GRACE_PERIOD = 1.0
EYE_MOVEMENT_GRACE_PERIOD = 1.0
